### ISSUE TITLE
Is the device_trackers not work?

### ISSUE THREAD

**Issue by RankesGitHub** [jonathanadams/Home-Assistant-Configuration#5]
Im very love this folder structure, it's the elegance of breakthrough the planet!
I see the phone device_tracker.jonathans_iphone_x in /entities/persons/jon.yaml. but I dont see anything in /entities/device_trackers. Is it working correct?

**Comment by jonathanadams** [comment]
The stricture of this config was not developed by me - its similar to the one from https://github.com/frenck/home-assistant-config

The iphone device tracker is added via the home assistant app automatically.
